server:
  port: 8888
  servlet:
    context-path: /adminui
spring:
  profiles: cluster
  application:
    name: cpaas-admin-ui
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  redis:
    database: 1
    #password: 
    cluster:
      max-redirects: 3
      nodes:
      - 127.0.0.1:7000
      - 127.0.0.1:7001
      - 127.0.0.1:7002
      - 127.0.0.1:7003
      - 127.0.0.1:7004
      - 127.0.0.1:7005
    lettuce:
      pool:
        max-active:  100 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 100 # 连接池中的最大空闲连接
        min-idle: 50 # 连接池中的最小空闲连接
        max-wait: 6000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
    timeout: 1000
logging:
  config: classpath:log4j2.xml